# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  emsservicesapi:
    image: emsservicesapi
    build:
      context: .
      dockerfile: src/EMS.Services.API/Dockerfile
    ports:
      - 5000:5000
